version: '1'

services:
  rmDB:
    image: postgres:15.7
    container_name:
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=
    volumes:
      - ./data:/var/lib/postgresql/data